CREATE TABLE occupation_table ( 
	id INT UNSIGNED NOT NULL AUTO_INCREMENT KEY, 
	d100 INT(4), 
	occupation VARCHAR(50), 
	trained_weapon VARCHAR(50),
	trade_goods VARCHAR(50)
);
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (1, "Alchemist", "Staff", "Oil, 1 flask");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (2, "Animal trainer", "Club", "Pony");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (3, "Armorer", "Hammer (as club)", "Iron helmet");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (4, "Astrologer", "Dagger", "Spyglass");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (5, "Barber", "Razor (as dagger)", "Scissors");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (6, "Beadle", "Staff", "Holy symbol");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (7, "Beekeeper", "Staff", "Jar of honey");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (8, "Blacksmith", "Hammer (as club)", "Steel tongs");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (9, "Butcher", "Cleaver (as axe)", "Side of beef");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (10, "Caravan guard", "Short sword", "Linen, 1 yard");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (11, "Cheesemaker", "Cudgel (as staff)", "Stinky cheese");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (12, "Cobbler", "Awl (as dagger)", "Shoehorn");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (13, "Confidence artist", "Dagger", "Quality cloak");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (14, "Cooper", "Crowbar (as club)", "Barrel");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (15, "Costermonger", "Knife (as dagger)", "Fruit");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (16, "Cutpurse", "Dagger", "Small chest");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (17, "Ditch digger", "Shovel (as staff)", "Fine dirt, 1 lb.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (18, "Dock worker", "Pole (as staff)", "1 late RPG book");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (19, "Dwarven apothecarist", "Cudgel (as staff)", "Steel vial");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (20, "Dwarven blacksmith", "Hammer (as club)", "Mithril, 1 oz.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (21, "Dwarven chest-maker", "Chisel (as dagger)", "Wood, 10 lbs.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (22, "Dwarven herder", "Staff", "Sow**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (23, "Dwarven miner", "Pick (as club)", "Lantern");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (24, "Dwarven miner", "Pick (as club)", "Lantern");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (25, "Dwarven mushroom-farmer", "Shovel (as staff)", "Sack");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (26, "Dwarven rat-catcher", "Club", "Net");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (27, "Dwarven stonemason", "Hammer", "Fine stone, 10 lbs.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (28, "Dwarven stonemason", "Hammer", "Fine stone, 10 lbs.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (29, "Elven artisan", "Staff", "Clay, 1 lb.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (30, "Elven barrister", "Quill (as dart)", "Book");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (31, "Elven chandler", "Scissors (as dagger)", "Candles, 20");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (32, "Elven falconer", "Dagger", "Falcon");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (33, "Elven forester", "Staff", "Herbs, 1 lb.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (34, "Elven forester", "Staff", "Herbs, 1 lb.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (35, "Elven glassblower", "Hammer (as club)", "Glass beads");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (36, "Elven navigator", "Shortbow", "Spyglass");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (37, "Elven sage", "Dagger", "Parchment and quill pen");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (38, "Elven sage", "Dagger", "Parchment and quill pen");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (39, "Farmer*", "Pitchfork (as spear)", "Hen**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (40, "Farmer*", "Pitchfork (as spear)", "Hen**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (41, "Farmer*", "Pitchfork (as spear)", "Hen**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (42, "Farmer*", "Pitchfork (as spear)", "Hen**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (43, "Farmer*", "Pitchfork (as spear)", "Hen**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (44, "Farmer*", "Pitchfork (as spear)", "Hen**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (45, "Farmer*", "Pitchfork (as spear)", "Hen**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (46, "Farmer*", "Pitchfork (as spear)", "Hen**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (47, "Farmer*", "Pitchfork (as spear)", "Hen**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (48, "Fortune-teller", "Dagger", "Tarot deck");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (49, "Gambler", "Club", "Dice");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (50, "Gongfarmer", "Trowler (as dagger)", "Sack of night soil");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (51, "Grave digger", "Shovel (as staff)", "Trowel");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (52, "Grave digger", "Shovel (as staff)", "Trowel");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (53, "Guild beggar", "Sling", "Crutches");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (54, "Guild beggar", "Sling", "Crutches");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (55, "Halfing chicken butcher", "Hand axe", "Chicken meat, 5 lbs.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (56, "Halfing dyer", "Staff", "Fabric, 3 yards");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (57, "Halfing dyer", "Staff", "Fabric, 3 yards");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (58, "Halfing glovemaker", "Awl (as dagger)", "Gloves, 4 pairs");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (59, "Halfing gypsy", "Sling", "Hex doll");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (60, "Halfing haberdasher", "Scissors (as dagger)", "Fine suits, 3 sets");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (61, "Halfing mariner", "Knife (as dagger)", "Sailcloth, 2 yards");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (62, "Halfing moneylender", "Short sword", "5 gp, 10 sp, 200 cp");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (63, "Halfing trader", "Short sword", "20 sp");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (64, "Halfing vagrant", "Club", "Begging bowl");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (65, "Healer", "Club", "Holy water, 1 vial");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (66, "Herbalist", "Club", "Herbs, 1 lb.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (67, "Herder", "Staff", "Herding dog**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (68, "Hunter", "Shortbow", "Deer pelt");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (69, "Hunter", "Shortbow", "Deer pelt");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (70, "Indentured servant", "Staff", "Locket");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (71, "Jester", "Dart", "Silk clothes");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (72, "Jeweler", "Dagger", "Gem worth 20 gp");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (73, "Locksmith", "Dagger", "Fine tools");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (74, "Mendicant", "Club", "Cheese dip");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (75, "Mercenary", "Longsword", "Hide armor");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (76, "Merchant", "Dagger", "Ukulele");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (77, "Miller/baker", "Club", "Flour, 1lb.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (78, "Minstrel", "Dagger", "Ukulele");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (79, "Noble", "Longsword", "Gold ring worth 10 gp");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (80, "Orphan", "Club", "Rag doll");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (81, "Ostler", "Staff", "Bridle");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (82, "Outlaw", "Short sword", "Leather armor");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (83, "Rope maker", "Knife (as dagger)", "Rope, 100'");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (84, "Scribe", "Dart", "Parchment, 10 sheets");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (85, "Shaman", "Mace", "Herb, 1 lb.");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (86, "Slave", "Club", "Strange-looking rock");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (87, "Smuggler", "Sling", "Waterproof sack");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (88, "Soldier", "Spear", "Shield");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (89, "Squire", "Longsword", "Steel helmet");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (90, "Squire", "Longsword", "Steel helmet");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (91, "Tax collector", "Longsword", "100 cp");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (92, "Trapper", "Sling", "Badger pelt");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (93, "Trapper", "Sling", "Badger pelt");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (94, "Urchin", "Stick (as club)", "Begging bowl");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (95, "Wainwright", "Club", "Pushcart**");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (96, "Weaver", "Dagger", "Fine suit of clothes");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (97, "Wizard's apprentice", "Dagger", "Black grimoire");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (98, "Woodcutter", "Handaxe", "Bundle of wood");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (99, "Woodcutter", "Handaxe", "Bundle of wood");
insert into occupation_table (d100, occupation, trained_weapon, trade_goods) values (100, "Woodcutter", "Handaxe", "Bundle of wood");

